### ISSUE TITLE
Zero body margin is being removed

### ISSUE THREAD

**Issue by Andrew-Starr** [webmandesign/global-styles-mods#1]
Many thanks for creating this plugin. I really appreciate what this is trying to accomplish.

I noticed that the zero margin on the `body` element is being removed.

The result of this is that the browser adds its own default margin around the body, resulting in full-width blocks not going full wide, and blocks that a user may want to extend to the top/bottom (e.g. header or footer) appearing with spacing above/below.

Would it be possible to add an exception to the `body { margin: 0; }` being converted to `:root { margin: 0; }`?

**Comment by webmandesign** [comment]
Hi @Andrew-Starr,

This shouldn't be the case. WordPress global styles does not produce `body { margin: 0; }` - at least not for my theme.

Do you use an FSE (full site editing) theme? If so, then please note that you should not use this plugin. It was created only for themes that support Gutenberg editor but are not FSE ready.

Can you maybe provide URL to your affected website/page so I can double check? Thanks.

**Comment by Andrew-Starr** [comment]
Yes the issue is when using FSE block themes.

My bad. I didn't realise the plugin shouldn't be used with block themes, and I didn't notice this limitation stated anywhere in the readme or description. It seems to work well with a block theme otherwise.

**Comment by webmandesign** [comment]
In that case you don't have to use this plugin. The FSE theme should work perfectly fine and you should not experience issues. If you do, please contact your theme support for help.

WordPress 5.9 introduced a lot of issues, but from my perspective they all should be related to Gutenberg-ready non-FSE themes though.

I will update the description of the plugin for more info.

Can you please share if you are using FSE theme on an existing website? As from top of my head I think that's the only possible case where the issues might occur &rarr; meaning with existing content. In that case the global styles issue is even bigger than I thought, unfortunately...
